twilio: # Twilio SMS gateway configuration
  accountId:
  accountToken:
  numbers:
   - 1234567890
  messagingServicesId:
  localDomain: # The domain Twilio can call back to.

attachments: # AWS S3 configuration
  accessKey: none
  accessSecret: none

  # Name of the S3 bucket (needs to have been created)
  # for attachments to go.  Should be configured with
  # correct permissions.
  bucket: none

profiles: # AWS S3 configuration
  accessKey:
  accessSecret:
  bucket:
  region:

directory: # Redis server configuration for TS directory
  url:

cache: # Redis server configuration for general purpose caching
  url:

messageStore: # Postgres database configuration for message store
  driverClass: org.postgresql.Driver
  user:
  password:
  url:
  initialSize: 1
  minSize: 1
  maxSize: 3

database: # Postgres database configuration for account store
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver

  # the username
  user:

  # the password
  password:

  # the JDBC URL
  url:
  initialSize: 1
  minSize: 1
  maxSize: 3

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8

server:
  applicationConnectors:
    - type: http
      port:
#  adminConnectors:
#    - type: http
#      port:

turn:
  secret: none
  uris:
   - none

push:
  queueSize: # Size of push pending queue

apn: # Apple Push Notifications configuration
  bundleId:
  pushCertificate:
  pushKey:
  sandbox: true

gcm: # GCM Configuration
  senderId:
  apiKey:


limits:
  smsDestination:
    bucketSize: 50000
    leakRatePerMinute: 50000
  voiceDestination:
    bucketSize: 50000
    leakRatePerMinute: 50000
  voiceDestinationDaily:
    bucketSize: 50000
    leakRatePerMinute: 50000
  verifyNumber:
    bucketSize: 50000
    leakRatePerMinute: 50000
  attachments:
    bucketSize: 50000
    leakRatePerMinute: 50000
  contactQueries:
    bucketSize: 50000
    leakRatePerMinute: 50000
  prekeys:
    bucketSize: 50000
    leakRatePerMinute: 50000
  messages:
    bucketSize: 50000
    leakRatePerMinute: 50000
  allocateDevice:
    bucketSize: 50000
    leakRatePerMinute: 50000
  verifyDevice:
    bucketSize: 50000
    leakRatePerMinute: 50000
  turnAllocations:
    bucketSize: 50000
    leakRatePerMinute: 50000