twilio: # Twilio SMS gateway configuration
  accountId:
  accountToken:
  numbers:
   - 1234567890
  localDomain: # The domain Twilio can call back to.

push: # GCM/APN push server configuration
  host: none
  port: 1234
  username: none
  password: none

s3: # AWS S3 configuration
  accessKey: none
  accessSecret: none

  # Name of the S3 bucket (needs to have been created)
  # for attachments to go.  Should be configured with
  # correct permissions.
  attachmentsBucket: none

directory: # Redis server configuration for TS directory
  url:

cache: # Redis server configuration for general purpose caching
  url:

websocket:
  enabled: true

messageStore: # Postgres database configuration for message store
  driverClass: org.postgresql.Driver
  user:
  password:
  url:

database: # Postgres database configuration for account store
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver

  # the username
  user:

  # the password
  password:

  # the JDBC URL
  url:

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8

server:
  applicationConnectors:
    - type: http
      port:
#  adminConnectors:
#    - type: http
#      port:

turn:
  secret: none
  uris:
   - none