twilio: # Twilio SMS gateway configuration
  accountId:
  accountToken:
  numbers:
   - 1234567890
  messagingServicesId:
  localDomain: # The domain Twilio can call back to.

push:
  queueSize: # Size of push pending queue

attachments: # AWS S3 configuration
  accessKey: none
  accessSecret: none

  # Name of the S3 bucket (needs to have been created)
  # for attachments to go.  Should be configured with
  # correct permissions.
  bucket: none

profiles: # AWS S3 configuration
  accessKey:
  accessSecret:
  bucket:
  region:

cache: # Redis server configuration for cache cluster
  url:

directory: # Redis server configuration for directory cluster
  url:

messageStore: # Postgresql database configuration for message store
  driverClass: org.postgresql.Driver
  user:
  password:
  url:
  initialSize: 1
  minSize: 1
  maxSize: 3

s3: # AWS S3 configuration
  accessKey:
  accessSecret:
  attachmentsBucket:

database: # Postgresql database configuration
  driverClass: org.postgresql.Driver
  # the JDBC URL
  url:
  initialSize: 1
  minSize: 1
  maxSize: 3

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8

server:
  applicationConnectors:
    - type: http
      port:
#  adminConnectors:
#    - type: http
#      port:

turn:
  secret: none
  uris:
   - none

apn: # Apple Push Notifications configuration
  bundleId:
  pushCertificate:
  pushKey:
  sandbox: false

gcm: # GCM Configuration
  senderId:
  apiKey:
